var cors = require("cors");
const express = require("express");
const app = express();
const nodemailer = require("nodemailer");
const port = 8000;
require("dotenv").config({
  path: require("path").resolve(__dirname, "../touch .env"),
});
const http = require("http");

const server = http.createServer(app);

app.use(express.json());
app.use(cors());

app.post("/send-feedback", async (req, res) => {
  const { name, mailid, message, rating } = req.body;

  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });

  const mailOptions = {
    from: process.env.EMAIL_USER,
    to: process.env.EMAIL_RECEIVER,
    subject: `Feedback from ${name}`,
    attachments: [
      {
        filename: "logo.png",
        path: __dirname + "/../src/assets/logo.png",
        cid: "logo@cid",
      },
    ],
    html: `<div style="font-family: Arial, sans-serif; padding: 20px; background-color: #f4f4f4;">
  <div style="max-width: 600px; margin: auto; background-color: #ffffff; padding: 30px; border-radius: 8px; box-shadow: 0 0 10px rgba(0,0,0,0.1);">

    <div style="text-align: center; display: flex; justify-content: center; padding: 20px; margin-bottom: 20px; background-color: #4CECD6">
      <img src="cid:logo@cid" alt="Vincent Therapies Logo" style="width: 120px; height: auto; border-radius: 50%; display: block; margin: auto;" />
    </div>

    <p style="font-size: 18px; color: #333;"><strong>Hello Roshan Vincent,</strong></p>
    <p style="font-size: 16px; color: #555;">You have received a new feedback from <strong>${name}</strong>.</p>

    <hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;" />
    <p style="font-size: 16px; color: #333;"><strong>Gmail ID:</strong> ${mailid}</p>

    <p style="font-size: 16px; color: #333;"><strong>Rating:</strong>
      <span style="font-size: 18px;">
        ${[1, 2, 3, 4, 5]
          .map(
            (i) => `
          <span style="color: ${
            i <= rating ? "#FFD700" : "#ccc"
          };">&#9733;</span>
        `
          )
          .join("")}
      </span>
    </p>

    <p style="font-size: 16px; color: #333;"><strong>Message:</strong></p>
    <p style="font-size: 15px; color: #555; background-color: #f9f9f9; padding: 15px; border-radius: 6px;">${message}</p>

    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;" />

    <p style="font-size: 14px; color: #aaa; text-align: center;">
      This email was automatically generated by the feedback system.
    </p>
  </div>
</div>
`,
  };

  try {
    await transporter.sendMail(mailOptions);
    res.status(200).json({ message: "Feedback sent successfully" });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: err });
  }
});
app.post("/contact", async (req, res) => {
  const { name, phone, email, message } = req.body;
  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });
  const mailOptions = {
    from: process.env.EMAIL_USER,
    to: process.env.EMAIL_RECEIVER,
    subject: `Message from ${name}`,
    attachments: [
      {
        filename: "logo.png",
        path: __dirname + "/../src/assets/logo.png",
        cid: "logo@cid",
      },
    ],
    html: `<div style="font-family: Arial, sans-serif; padding: 20px; background-color: #f4f4f4;">
  <div style="max-width: 600px; margin: auto; background-color: #ffffff; padding: 30px; border-radius: 8px; box-shadow: 0 0 10px rgba(0,0,0,0.1);">

    <div style="text-align: center; display: flex; justify-content: center; padding: 20px; margin-bottom: 20px; background-color: #4CECD6">
      <img src="cid:logo@cid" alt="Vincent Therapies Logo" style="width: 120px; height: auto; border-radius: 50%; display: block; margin: auto;" />
    </div>

    <p style="font-size: 18px; color: #333;"><strong>Hello Roshan Vincent,</strong></p>
    <p style="font-size: 16px; color: #555;">You have received a new message from <strong>${name}</strong>.</p>

    <hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;" />
    <p style="font-size: 16px; color: #333;"><strong>Gmail ID:</strong> ${email}</p>
    <p style="font-size: 16px; color: #333;"><strong>Phone Number:</strong> ${phone}</p>


    <p style="font-size: 16px; color: #333;"><strong>Message:</strong></p>
    <p style="font-size: 15px; color: #555; background-color: #f9f9f9; padding: 15px; border-radius: 6px;">${message}</p>

    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;" />

    <p style="font-size: 14px; color: #aaa; text-align: center;">
      This email was automatically generated by the feedback system.
    </p>
  </div>
</div>
`,
  };
  try {
    await transporter.sendMail(mailOptions);
    res.status(200).json({ message: "Message sent successfully" });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: err });
  }
});
server.listen(port, () => {
  console.log(`VincentTherapies Backend listening on port ${port}`);
});
